# This requires vhs installed from source for the updated theme and screenshot command
# go install github.com/charmbracelet/vhs@main
Output "../../src/content/docs/how-to/develop-apps/color-eyre/demo.gif"
Set Theme "Aardvark Blue"
Set Width 1200
Set Height 800
Type "cargo run" Enter
Sleep 2s
Type "q"
Sleep 2s
Type "cargo run" Enter
Sleep 2s
Type "p"
Sleep 2s
Type "cargo run" Enter
Sleep 2s
Type "e"
Sleep 2s
