# configuration for https://github.com/crate-ci/typos

[default.extend-words]
ratatui = "ratatui"
iterm2 = "iTerm2"
iterm = "iTerm2"

[type.md]
extend-ignore-re = [
  "\\[[[:xdigit:]]{7}\\]\\(https://github.com/ratatui/ratatui/commit/[[:xdigit:]]{40}\\)",
]

[files]
extend-exclude = ["public/built-with-ratatui/badge.svg"]
