name: Check PR

on:
  pull_request:
    branches:
      - main
      # release branches
      - ratatui-*.*
  merge_group:

# ensure that the workflow is only triggered once per PR,  subsequent pushes to the PR will cancel
# and restart the workflow. See https://docs.github.com/en/actions/using-jobs/using-concurrency
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  check-lfs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: nschloe/action-cached-lfs-checkout@v1
      - name: Get images
        run:
          find . -regextype posix-awk -regex ".*\.(png|gif)" -type f | cut -d"/" -f2- | sort >
          /tmp/images
      - name: Get lfs files
        run: git lfs ls-files | cut -d" " -f3 | sort > /tmp/lfs-files
      - name: Diff
        run: diff --color=always /tmp/images /tmp/lfs-files
